services:
    db:
        image: postgres:latest
        environment:
          POSTGRES_DB: ${PGDATABASE}
          POSTGRES_USER: ${PGUSER}
          POSTGRES_PASSWORD: ${PGPASSWORD}
          POSTGRES_HOST: ${PGHOST}
        ports:
            - ${PGPORT}:5432
        env_file:
          - .env
        volumes:
            - pg-data-greenitforward:/var/lib/postgresql/data
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready" ]
          interval: 5s
          timeout: 5s
          retries: 5

volumes:
    pg-data-greenitforward:
    node_modules: